import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import css from './Home.module.css';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TanStackProvider>
          <Header />
          <main>
            <div className={css.container}>
              <h1 className={css.title}>Welcome to NoteHub</h1>
              <p className={css.description}>
                NoteHub is a simple and efficient application designed for managing personal notes.
                It helps keep your thoughts organized and accessible in one place, whether you are
                at home or on the go.
              </p>
              <p className={css.description}>
                The app provides a clean interface for writing, editing, and browsing notes. With
                support for keyword search and structured organization, NoteHub offers a streamlined
                experience for anyone who values clarity and productivity.
              </p>
            </div>
            {children}
          </main>
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
